/*
 * Copyright (C) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Mocks generated by Mockito for the ohos IAP Kit wrappers.
// 原安卓版使用 pigeon 生成的 BillingClientManager 的 mock，
// 鸿蒙版不使用 pigeon 和 BillingClientManager，而是使用 MethodChannel 的
// IKPaymentQueueWrapper，因此 mock 类不再需要。
//
// 原安卓mock内容（注释保留）：
// class MockBillingClientManager extends _i1.Mock
//     implements _i2.BillingClientManager {
//   MockBillingClientManager() {
//     _i1.throwOnMissingStub(this);
//   }
//   ...
// }
//
// 改造原因：鸿蒙版 IKPaymentQueueWrapper 基于 MethodChannel 直接通信，
// 测试时使用 MethodChannel 的 setMockMethodCallHandler 模拟平台响应，
// 不需要 Mockito mock 类。此文件保留为空。

// 如需后续添加其他 mock 类，可在此处添加。
