/*
 * Copyright (C) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Autogenerated-like message classes for OHOS quick actions.
// Since Pigeon does not currently support OHOS targets, these classes
// are manually written following the same pattern.

import 'dart:async';

import 'package:flutter/services.dart';

/// Home screen quick-action shortcut item.
class ShortcutItemMessage {
  ShortcutItemMessage({
    required this.type,
    required this.localizedTitle,
    this.localizedSubtitle,
    this.icon,
  });

  /// The identifier of this item; should be unique within the app.
  String type;

  /// Localized title of the item.
  String localizedTitle;

  /// Localized subtitle of the item.
  ///
  /// OHOS does not render a subtitle for static shortcuts, but the field is
  /// preserved for parity with the iOS implementation so that data is not
  /// silently dropped across the platform channel.
  String? localizedSubtitle;

  /// Name of native resource to be displayed as the icon for this item.
  String? icon;

  Object encode() {
    return <Object?>[
      type,
      localizedTitle,
      localizedSubtitle,
      icon,
    ];
  }

  static ShortcutItemMessage decode(Object result) {
    result as List<Object?>;
    return ShortcutItemMessage(
      type: result[0]! as String,
      localizedTitle: result[1]! as String,
      localizedSubtitle: result[2] as String?,
      icon: result[3] as String?,
    );
  }
}

class _OhosQuickActionsApiCodec extends StandardMessageCodec {
  const _OhosQuickActionsApiCodec();

  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is ShortcutItemMessage) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:
        return ShortcutItemMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Host API for OHOS quick actions (calls from Dart to native).
class OhosQuickActionsApi {
  OhosQuickActionsApi({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;

  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _OhosQuickActionsApiCodec();

  /// Checks for, and returns the action that launched the app.
  Future<String?> getLaunchAction() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
      'dev.flutter.pigeon.quick_actions_ohos.OhosQuickActionsApi.getLaunchAction',
      codec,
      binaryMessenger: _binaryMessenger,
    );
    final List<Object?>? replyList = await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return (replyList[0] as String?);
    }
  }

  /// Sets the dynamic shortcuts for the app.
  Future<void> setShortcutItems(
      List<ShortcutItemMessage?> arg_itemsList) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
      'dev.flutter.pigeon.quick_actions_ohos.OhosQuickActionsApi.setShortcutItems',
      codec,
      binaryMessenger: _binaryMessenger,
    );
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_itemsList]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  /// Removes all dynamic shortcuts.
  Future<void> clearShortcutItems() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
      'dev.flutter.pigeon.quick_actions_ohos.OhosQuickActionsApi.clearShortcutItems',
      codec,
      binaryMessenger: _binaryMessenger,
    );
    final List<Object?>? replyList = await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }
}

/// Flutter API for OHOS quick actions (calls from native to Dart).
abstract class OhosQuickActionsFlutterApi {
  static const MessageCodec<Object?> codec = StandardMessageCodec();

  /// Sends a string representing a shortcut from the native platform to the app.
  void launchAction(String action);

  static void setup(
    OhosQuickActionsFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
  }) {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
      'dev.flutter.pigeon.quick_actions_ohos.OhosQuickActionsFlutterApi.launchAction',
      codec,
      binaryMessenger: binaryMessenger,
    );
    if (api == null) {
      channel.setMessageHandler(null);
    } else {
      channel.setMessageHandler((Object? message) async {
        assert(
          message != null,
          'Argument for dev.flutter.pigeon.quick_actions_ohos.OhosQuickActionsFlutterApi.launchAction was null.',
        );
        final List<Object?> args = (message as List<Object?>?)!;
        final String? arg_action = args[0] as String?;
        assert(
          arg_action != null,
          'Argument for dev.flutter.pigeon.quick_actions_ohos.OhosQuickActionsFlutterApi.launchAction was null, expected non-null String.',
        );
        api.launchAction(arg_action!);
        return;
      });
    }
  }
}
