// Mocks generated by Mockito 5.4.6 from annotations
// in webview_flutter_ohos/test/ohos_navigation_delegate_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:webview_flutter_ohos/src/ohos_webview.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeOhosObject_0 extends _i1.SmartFake implements _i2.OhosObject {
  _FakeOhosObject_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDownloadListener_1 extends _i1.SmartFake
    implements _i2.DownloadListener {
  _FakeDownloadListener_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HttpAuthHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpAuthHandler extends _i1.Mock implements _i2.HttpAuthHandler {
  MockHttpAuthHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> cancel() =>
      (super.noSuchMethod(
            Invocation.method(#cancel, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> proceed(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#proceed, [username, password]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> useHttpAuthUsernamePassword() =>
      (super.noSuchMethod(
            Invocation.method(#useHttpAuthUsernamePassword, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i2.OhosObject copy() =>
      (super.noSuchMethod(
            Invocation.method(#copy, []),
            returnValue: _FakeOhosObject_0(this, Invocation.method(#copy, [])),
          )
          as _i2.OhosObject);
}

/// A class which mocks [DownloadListener].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadListener extends _i1.Mock implements _i2.DownloadListener {
  MockDownloadListener() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void Function(String, String, String, String, int) get onDownloadStart =>
      (super.noSuchMethod(
            Invocation.getter(#onDownloadStart),
            returnValue:
                (
                  String url,
                  String userAgent,
                  String contentDisposition,
                  String mimetype,
                  int contentLength,
                ) {},
          )
          as void Function(String, String, String, String, int));

  @override
  _i2.DownloadListener copy() =>
      (super.noSuchMethod(
            Invocation.method(#copy, []),
            returnValue: _FakeDownloadListener_1(
              this,
              Invocation.method(#copy, []),
            ),
          )
          as _i2.DownloadListener);
}
