// Mocks generated by Mockito 5.4.4 from annotations
// in webview_flutter_ohos/test/ohos_webview_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:webview_flutter_ohos/src/ohos_webview.g.dart' as _i2;

import 'test_ohos_webview.g.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWebViewPoint_0 extends _i1.SmartFake implements _i2.WebViewPoint {
  _FakeWebViewPoint_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TestInstanceManagerHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestInstanceManagerHostApi extends _i1.Mock
    implements _i3.TestInstanceManagerHostApi {
  MockTestInstanceManagerHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TestOhosObjectHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestOhosObjectHostApi extends _i1.Mock
    implements _i3.TestOhosObjectHostApi {
  MockTestOhosObjectHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void dispose(int? identifier) => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [identifier],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TestWebViewHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestWebViewHostApi extends _i1.Mock
    implements _i3.TestWebViewHostApi {
  MockTestWebViewHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void create(int? instanceId) => super.noSuchMethod(
        Invocation.method(
          #create,
          [instanceId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void loadData(
    int? instanceId,
    String? data,
    String? mimeType,
    String? encoding,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #loadData,
          [
            instanceId,
            data,
            mimeType,
            encoding,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void loadDataWithBaseUrl(
    int? instanceId,
    String? baseUrl,
    String? data,
    String? mimeType,
    String? encoding,
    String? historyUrl,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #loadDataWithBaseUrl,
          [
            instanceId,
            baseUrl,
            data,
            mimeType,
            encoding,
            historyUrl,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void loadUrl(
    int? instanceId,
    String? url,
    Map<String?, String?>? headers,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #loadUrl,
          [
            instanceId,
            url,
            headers,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void postUrl(
    int? instanceId,
    String? url,
    _i4.Uint8List? data,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #postUrl,
          [
            instanceId,
            url,
            data,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String? getUrl(int? instanceId) => (super.noSuchMethod(Invocation.method(
        #getUrl,
        [instanceId],
      )) as String?);

  @override
  bool canGoBack(int? instanceId) => (super.noSuchMethod(
        Invocation.method(
          #canGoBack,
          [instanceId],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool canGoForward(int? instanceId) => (super.noSuchMethod(
        Invocation.method(
          #canGoForward,
          [instanceId],
        ),
        returnValue: false,
      ) as bool);

  @override
  void goBack(int? instanceId) => super.noSuchMethod(
        Invocation.method(
          #goBack,
          [instanceId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void goForward(int? instanceId) => super.noSuchMethod(
        Invocation.method(
          #goForward,
          [instanceId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reload(int? instanceId) => super.noSuchMethod(
        Invocation.method(
          #reload,
          [instanceId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearCache(
    int? instanceId,
    bool? includeDiskFiles,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [
            instanceId,
            includeDiskFiles,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<String?> evaluateJavascript(
    int? instanceId,
    String? javascriptString,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #evaluateJavascript,
          [
            instanceId,
            javascriptString,
          ],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  String? getTitle(int? instanceId) => (super.noSuchMethod(Invocation.method(
        #getTitle,
        [instanceId],
      )) as String?);

  @override
  void scrollTo(
    int? instanceId,
    int? x,
    int? y,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #scrollTo,
          [
            instanceId,
            x,
            y,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void scrollBy(
    int? instanceId,
    int? x,
    int? y,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #scrollBy,
          [
            instanceId,
            x,
            y,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int getScrollX(int? instanceId) => (super.noSuchMethod(
        Invocation.method(
          #getScrollX,
          [instanceId],
        ),
        returnValue: 0,
      ) as int);

  @override
  int getScrollY(int? instanceId) => (super.noSuchMethod(
        Invocation.method(
          #getScrollY,
          [instanceId],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i2.WebViewPoint getScrollPosition(int? instanceId) => (super.noSuchMethod(
        Invocation.method(
          #getScrollPosition,
          [instanceId],
        ),
        returnValue: _FakeWebViewPoint_0(
          this,
          Invocation.method(
            #getScrollPosition,
            [instanceId],
          ),
        ),
      ) as _i2.WebViewPoint);

  @override
  void setWebContentsDebuggingEnabled(bool? enabled) => super.noSuchMethod(
        Invocation.method(
          #setWebContentsDebuggingEnabled,
          [enabled],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setWebViewClient(
    int? instanceId,
    int? webViewClientInstanceId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setWebViewClient,
          [
            instanceId,
            webViewClientInstanceId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addJavaScriptChannel(
    int? instanceId,
    int? javaScriptChannelInstanceId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #addJavaScriptChannel,
          [
            instanceId,
            javaScriptChannelInstanceId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeJavaScriptChannel(
    int? instanceId,
    int? javaScriptChannelInstanceId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #removeJavaScriptChannel,
          [
            instanceId,
            javaScriptChannelInstanceId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDownloadListener(
    int? instanceId,
    int? listenerInstanceId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setDownloadListener,
          [
            instanceId,
            listenerInstanceId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setWebChromeClient(
    int? instanceId,
    int? clientInstanceId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setWebChromeClient,
          [
            instanceId,
            clientInstanceId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setBackgroundColor(
    int? instanceId,
    int? color,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setBackgroundColor,
          [
            instanceId,
            color,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TestWebSettingsHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestWebSettingsHostApi extends _i1.Mock
    implements _i3.TestWebSettingsHostApi {
  MockTestWebSettingsHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void create(
    int? instanceId,
    int? webViewInstanceId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #create,
          [
            instanceId,
            webViewInstanceId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDomStorageEnabled(
    int? instanceId,
    bool? flag,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setDomStorageEnabled,
          [
            instanceId,
            flag,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setJavaScriptCanOpenWindowsAutomatically(
    int? instanceId,
    bool? flag,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setJavaScriptCanOpenWindowsAutomatically,
          [
            instanceId,
            flag,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSupportMultipleWindows(
    int? instanceId,
    bool? support,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setSupportMultipleWindows,
          [
            instanceId,
            support,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setJavaScriptEnabled(
    int? instanceId,
    bool? flag,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setJavaScriptEnabled,
          [
            instanceId,
            flag,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setUserAgentString(
    int? instanceId,
    String? userAgentString,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setUserAgentString,
          [
            instanceId,
            userAgentString,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setMediaPlaybackRequiresUserGesture(
    int? instanceId,
    bool? require,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setMediaPlaybackRequiresUserGesture,
          [
            instanceId,
            require,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSupportZoom(
    int? instanceId,
    bool? support,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setSupportZoom,
          [
            instanceId,
            support,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLoadWithOverviewMode(
    int? instanceId,
    bool? overview,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setLoadWithOverviewMode,
          [
            instanceId,
            overview,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setUseWideViewPort(
    int? instanceId,
    bool? use,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setUseWideViewPort,
          [
            instanceId,
            use,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDisplayZoomControls(
    int? instanceId,
    bool? enabled,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setDisplayZoomControls,
          [
            instanceId,
            enabled,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setBuiltInZoomControls(
    int? instanceId,
    bool? enabled,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setBuiltInZoomControls,
          [
            instanceId,
            enabled,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAllowFileAccess(
    int? instanceId,
    bool? enabled,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setAllowFileAccess,
          [
            instanceId,
            enabled,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTextZoom(
    int? instanceId,
    int? textZoom,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setTextZoom,
          [
            instanceId,
            textZoom,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setBackgroundColor(
    int? instanceId,
    int? color,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setBackgroundColor,
          [
            instanceId,
            color,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAllowFullScreenRotate(
    int? instanceId,
    bool? enabled,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setAllowFullScreenRotate,
          [
            instanceId,
            enabled,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getUserAgentString(int? instanceId) => (super.noSuchMethod(
        Invocation.method(
          #getUserAgentString,
          [instanceId],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getUserAgentString,
            [instanceId],
          ),
        ),
      ) as String);
}

/// A class which mocks [TestWebChromeClientHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestWebChromeClientHostApi extends _i1.Mock
    implements _i3.TestWebChromeClientHostApi {
  MockTestWebChromeClientHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void create(int? instanceId) => super.noSuchMethod(
        Invocation.method(
          #create,
          [instanceId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSynchronousReturnValueForOnShowFileChooser(
    int? instanceId,
    bool? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setSynchronousReturnValueForOnShowFileChooser,
          [
            instanceId,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSynchronousReturnValueForOnConsoleMessage(
    int? instanceId,
    bool? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setSynchronousReturnValueForOnConsoleMessage,
          [
            instanceId,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSynchronousReturnValueForOnJsAlert(
    int? instanceId,
    bool? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setSynchronousReturnValueForOnJsAlert,
          [
            instanceId,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSynchronousReturnValueForOnJsConfirm(
    int? instanceId,
    bool? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setSynchronousReturnValueForOnJsConfirm,
          [
            instanceId,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSynchronousReturnValueForOnJsPrompt(
    int? instanceId,
    bool? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setSynchronousReturnValueForOnJsPrompt,
          [
            instanceId,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TestWebViewClientHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestWebViewClientHostApi extends _i1.Mock
    implements _i3.TestWebViewClientHostApi {
  MockTestWebViewClientHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void create(int? instanceId) => super.noSuchMethod(
        Invocation.method(
          #create,
          [instanceId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSynchronousReturnValueForShouldOverrideUrlLoading(
    int? instanceId,
    bool? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setSynchronousReturnValueForShouldOverrideUrlLoading,
          [
            instanceId,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TestJavaScriptChannelHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestJavaScriptChannelHostApi extends _i1.Mock
    implements _i3.TestJavaScriptChannelHostApi {
  MockTestJavaScriptChannelHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void create(
    int? instanceId,
    String? channelName,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #create,
          [
            instanceId,
            channelName,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TestWebStorageHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestWebStorageHostApi extends _i1.Mock
    implements _i3.TestWebStorageHostApi {
  MockTestWebStorageHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void create(int? instanceId) => super.noSuchMethod(
        Invocation.method(
          #create,
          [instanceId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deleteAllData(int? instanceId) => super.noSuchMethod(
        Invocation.method(
          #deleteAllData,
          [instanceId],
        ),
        returnValueForMissingStub: null,
      );
}
