// Mocks generated by Mockito 5.4.4 from annotations
// in webview_flutter_ohos/test/ohos_webview_cookie_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;

import 'test_ohos_webview.g.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TestCookieManagerHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestCookieManagerHostApi extends _i1.Mock
    implements _i2.TestCookieManagerHostApi {
  MockTestCookieManagerHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void attachInstance(int? instanceIdentifier) => super.noSuchMethod(
        Invocation.method(
          #attachInstance,
          [instanceIdentifier],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setCookie(
    int? identifier,
    String? url,
    String? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setCookie,
          [
            identifier,
            url,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<bool> removeAllCookies(int? identifier) => (super.noSuchMethod(
        Invocation.method(
          #removeAllCookies,
          [identifier],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  void setAcceptThirdPartyCookies(
    int? identifier,
    int? webViewIdentifier,
    bool? accept,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setAcceptThirdPartyCookies,
          [
            identifier,
            webViewIdentifier,
            accept,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TestInstanceManagerHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestInstanceManagerHostApi extends _i1.Mock
    implements _i2.TestInstanceManagerHostApi {
  MockTestInstanceManagerHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
